name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - uses: astral-sh/setup-uv@v5
    
    - name: Check formatting with Ruff
      run: uv run ruff format --check src tests examples
    
    - name: Check imports with isort
      run: uv run isort --check-only --profile black src tests examples
    
    - name: Lint with Ruff
      run: uv run ruff check src tests examples
    
    - name: Type check with mypy
      run: uv run mypy src
    
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - uses: astral-sh/setup-uv@v5
    
    - name: Run tests
      run: uv run pytest 