name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - uses: astral-sh/setup-uv@v5

    - name: Check for syntax errors
      run: uv run ruff check --no-fix --select PLE
    
    - name: Build package
      run: uv build
    
    - name: Test wheel and sdist
      run: |
        uv run --isolated --no-project --with pytest --with dist/*.whl tests/test_basic.py
        uv run --isolated --no-project --with pytest --with dist/*.tar.gz tests/test_basic.py
    
    - name: Publish to PyPI
      run: uv publish --trusted-publishing always 